### ISSUE TITLE
Document resolution behavior of `.`

### ISSUE THREAD

**Issue by varungandhi-src** [apple/tree-sitter-pkl#6]
Based on the grammar, there is an ambiguity whose resolution is not documented in the language reference:

The `<expr>.s` grammar form can potentially mean:
- Unqualified reference to method `s` on the object `<expr>` (not sure if these are allowed?)
- Reference to property `s` on the object `<expr>`
- If `<expr>` is a number, then `<expr>` as a duration in seconds

For the purpose of highlighting, one might want to give methods different highlighting than properties, and different from a unit of measure (which is type-like). In the general case, is this impossible to determine without type information?

**Comment by holzensp** [comment]
Pkl does something possibly unexpected with namespaces; property and function namespaces are _entirely different_. This means that `x.foo` and `x.foo()` resolve to different things (the former to a property `foo` and the latter to a _function_ `foo`). Without parentheses, it's _always_ a property. When `<expr>` is a number, `.s` is indeed a `Duration` in seconds. Mind you, that's not because of some magic in the language; [`s` simply _is a property on `Number`_](https://pkl-lang.org/package-docs/pkl/0.25.3/base/Number.html#s).
